import * as fs from "node:fs";
import * as path from "node:path";
import { parse, stringify } from "smol-toml";
import type { EnvData, EnvEntry, EnvServiceEntries } from "@iara/contracts";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

export function getEnvTomlPath(workspaceDir: string): string {
  return path.join(workspaceDir, "env.toml");
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

const VALID_KEY_RE = /^[A-Z][A-Z0-9_]*$/;

export function validateEnvKey(key: string): boolean {
  return VALID_KEY_RE.test(key);
}

export function validateEntries(entries: EnvEntry[]): void {
  for (const entry of entries) {
    if (!validateEnvKey(entry.key)) {
      throw new Error(`Invalid env key: "${entry.key}". Keys must match [A-Z][A-Z0-9_]*.`);
    }
  }
}

// ---------------------------------------------------------------------------
// TOML Read / Write
// ---------------------------------------------------------------------------

/**
 * Read and parse env.toml from a workspace directory.
 * Returns EnvData with per-service sections.
 */
export function readEnvToml(workspaceDir: string): EnvData {
  const filePath = getEnvTomlPath(workspaceDir);
  try {
    const content = fs.readFileSync(filePath, "utf-8");
    const parsed = parse(content);
    const services: EnvServiceEntries[] = [];

    for (const [name, section] of Object.entries(parsed)) {
      if (typeof section !== "object" || section === null || Array.isArray(section)) continue;
      const entries: EnvEntry[] = [];
      for (const [key, value] of Object.entries(section)) {
        entries.push({ key, value: String(value) });
      }
      services.push({ name, entries });
    }

    return { services };
  } catch {
    return { services: [] };
  }
}

/**
 * Write env.toml to a workspace directory from EnvServiceEntries[].
 */
export function writeEnvToml(workspaceDir: string, services: EnvServiceEntries[]): void {
  const filePath = getEnvTomlPath(workspaceDir);
  const doc: Record<string, Record<string, string>> = {};

  for (const svc of services) {
    const section: Record<string, string> = {};
    for (const entry of svc.entries) {
      section[entry.key] = entry.value;
    }
    doc[svc.name] = section;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, stringify(doc) + "\n");
}

/**
 * Delete env.toml from a workspace directory.
 */
export function deleteEnvToml(workspaceDir: string): void {
  try {
    fs.unlinkSync(getEnvTomlPath(workspaceDir));
  } catch {
    // File may not exist
  }
}

// ---------------------------------------------------------------------------
// Get env for a specific service (for injection into scripts)
// ---------------------------------------------------------------------------

/**
 * Read env vars for a specific service from env.toml.
 * Returns a flat Record<string, string> suitable for process.spawn({ env }).
 */
export function getEnvForService(
  workspaceDir: string,
  serviceName: string,
): Record<string, string> {
  const data = readEnvToml(workspaceDir);
  const svc = data.services.find((s) => s.name === serviceName);
  if (!svc) return {};
  const env: Record<string, string> = {};
  for (const entry of svc.entries) {
    env[entry.key] = entry.value;
  }
  return env;
}

// ---------------------------------------------------------------------------
// Generate .env files into repo worktrees (R2)
// ---------------------------------------------------------------------------

const DOTENV_HEADER = "# Generated by iara - do not edit. Source: env.toml\n";

/**
 * Generate flat .env files for each repo worktree from env.toml.
 * Only repo sections (matching repoNames) get .env files written.
 */
export function generateDotEnvFiles(workspaceDir: string, repoNames: string[]): void {
  const data = readEnvToml(workspaceDir);
  const repoSet = new Set(repoNames);

  for (const svc of data.services) {
    if (!repoSet.has(svc.name)) continue;
    const repoDir = path.join(workspaceDir, svc.name);
    if (!fs.existsSync(repoDir)) continue;

    const lines = svc.entries.map((e) => `${e.key}=${e.value}`);
    const content = DOTENV_HEADER + lines.join("\n") + (lines.length > 0 ? "\n" : "");
    fs.writeFileSync(path.join(repoDir, ".env"), content);
  }
}

// ---------------------------------------------------------------------------
// Port offset for workspace creation (R4.11)
// ---------------------------------------------------------------------------

const PORT_KEY_RE = /^PORT$|_PORT$/;

/**
 * Copy env.toml from source workspace, offsetting PORT values for repo sections.
 * Non-repo service sections keep their ports unchanged.
 */
export function copyEnvTomlWithPortOffset(
  sourceDir: string,
  targetDir: string,
  repoNames: string[],
  workspaceIndex: number,
): void {
  const data = readEnvToml(sourceDir);
  if (data.services.length === 0) return;

  const repoSet = new Set(repoNames);
  const offset = 20 * workspaceIndex;

  const offsetServices: EnvServiceEntries[] = data.services.map((svc) => {
    if (!repoSet.has(svc.name)) return svc;
    return {
      name: svc.name,
      entries: svc.entries.map((entry) => {
        if (PORT_KEY_RE.test(entry.key)) {
          const port = Number.parseInt(entry.value, 10);
          if (!Number.isNaN(port)) {
            return { key: entry.key, value: String(port + offset) };
          }
        }
        return entry;
      }),
    };
  });

  writeEnvToml(targetDir, offsetServices);
}
